language: java
jdk:
  - openjdk8

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
#  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: dzdevsoft@gmail.com

addons:
  sonarcloud:
    organization: "messaoudabdelatif"
    token:
      secure: travis encrypt 84bfeab9955af4f364eee6b09be0fcc8ab2f82c9 # encrypted value of your token